/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kieferlam_javafxblur_NativeBlur */

#ifndef _Included_com_kieferlam_javafxblur_NativeBlur
#define _Included_com_kieferlam_javafxblur_NativeBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kieferlam_javafxblur_NativeBlur
 * Method:    _extApplyBlur
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kieferlam_javafxblur_NativeBlur__1extApplyBlur
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
